workflows:
  full-test-workflow:
    name: Full Test Workflow
    environment:
      flutter: stable
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/build
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - flutter packages pub get
    artifacts:
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - chinnonsantos@gmail.com
      slack:
        channel: '#geral'
        notify_on_build_start: true
