workflows:
  test-only-workflow:
    name: Test Only Workflow
    environment:
      flutter: beta
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - flutter packages pub get
      - flutter analyze --no-pub
      - flutter test --no-pub
    artifacts:
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - chinnonsantos@gmail.com
      slack:
        channel: '#geral'
        notify_on_build_start: true
