name: full_testing_flutter
description: Flutter App's simplest automated full test.
version: 1.0.0
author: Chinnon Santos <chinnonsantos@gmail.com>
homepage: https://www.chinnonsantos.com.br
repository: https://github.com/chinnonsantos/full_testing_flutter
issue_tracker: https://github.com/chinnonsantos/full_testing_flutter/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/test
  test: ^1.6.3
  # https://pub.dev/packages/provider
  provider: ^3.1.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/pedantic
  pedantic: ^1.8.0+1

flutter:
  uses-material-design: true
